#!/usr/bin/env sh

set -e
filename=".env"
if [ ! -f "$filename" ]; then
    echo "Error: File .env not found."
    exit 1
fi
while IFS= read -r line; do
    if echo "$line" | grep -q '^[[:space:]]*$'; then
        continue
    fi
    case "$line" in
        \#*)
            continue
            ;;
    esac
    var_name=$(echo "$line" | cut -d '=' -f 1)

    var_value=$(echo "$line" | cut -d '=' -f 2-)
    if echo "$line" | grep -q '=' && [ -n "$var_name" ] && [ -n "$(echo "$var_value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')" ]; then
        export "$line"
        echo "Exported: $var_name=$(eval echo \$$var_name)"
    else
        echo "Ignored (wrong format or empty value): $line"
    fi
done < "$filename"
export PATH=${JAVA_HOME}"/bin":${M2_HOME}"/bin":${IDEMPIERE_REPOSITORY}:${PATH}
mvn -v
echo ${IDEMPIERE_REPOSITORY}

if [ "$1" = "clean" ]; then
    ./gradlew -q clean
    rm -f settings.properties
    exit 0
fi

./gradlew -q clean installDist
./build/install/idempiere-plugin-generator/bin/idempiere-plugin-generator
